name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dev deps
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt
      - name: Lint
        run: ruff check .
      - name: Format check
        run: ruff format --check . && black --check .
      - name: Type check
        run: mypy .
      - name: Tests
        run: pytest -q
      - name: Docs build
        run: mkdocs build --strict
      - name: Pre-commit (meta checks)
        run: pre-commit run --all-files
