name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11 (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Restore tool caches (mypy/ruff/pytest)
        uses: actions/cache@v4
        with:
          path: |
            .mypy_cache
            .ruff_cache
            .pytest_cache
          key: tools-${{ runner.os }}-py3.11-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            tools-${{ runner.os }}-py3.11-

      - name: Install dependencies
        run: make install

      - name: Run pre-commit hooks (all files)
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Run tests (with coverage)
        run: make test

      - name: Generate coverage HTML (no re-run)
        run: python -m coverage html

      - name: Generate coverage badge
        run: make badge

      - name: Lint
        run: make lint

      - name: Type check
        run: make type

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage.xml
            docs/badges/coverage.svg
            htmlcov
          if-no-files-found: ignore
