name: CI

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11 (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Restore tool caches (mypy/ruff/pytest)
        uses: actions/cache@v4
        with:
          path: |
            .mypy_cache
            .ruff_cache
            .pytest_cache
          key: tools-${{ runner.os }}-py3.11-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            tools-${{ runner.os }}-py3.11-

      - name: Install dependencies
        run: make install

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli@0.42.0

      - name: Format sources (code/markdown/json)
        run: |
          make fmt
          make format-md
          make fmt-json

      - name: Run checks (lint/type/test/stats + md lint)
        run: |
          make ci
          make lint-md

      - name: Generate Markdown (tracks + README table)
        run: make markdown

      - name: Run pre-commit hooks (final, strict)
        env:
          CI: true
        run: make precommit-all

      # Coverage generation and artifacts removed from CI.
