name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11 (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'

      - name: Restore tool caches (mypy/ruff/pytest)
        uses: actions/cache@v4
        with:
          path: |
            .mypy_cache
            .ruff_cache
            .pytest_cache
          key: tools-${{ runner.os }}-py3.11-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            tools-${{ runner.os }}-py3.11-

      - name: Install dev dependencies
        run: make install

      - name: Run tests (with coverage)
        run: make test

      - name: Generate coverage HTML (no re-run)
        run: python -m coverage html

      - name: Generate coverage badge
        run: make badge

      - name: Lint
        run: make lint

      - name: Type check
        run: make type

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage.xml
            docs/badges/coverage.svg
            htmlcov
          if-no-files-found: ignore

      - name: Build static site
        run: |
          python scripts/build_pages.py

      - name: Upload Pages artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
